-- +goose Up
ALTER TABLE hosts DROP COLUMN IF EXISTS public_ip;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS ip_mapped BOOLEAN NOT NULL DEFAULT FALSE;

-- +goose Down
ALTER TABLE hosts DROP COLUMN IF EXISTS ip_mapped;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS public_ip VARCHAR(45);
